export const BACKGROUND_COLOR__ORDER_STATUS__RECEIVED = '#feffb3';
export const BACKGROUND_COLOR__ORDER_STATUS__ASSIGNED = '#c0ffb3';
export const BACKGROUND_COLOR__ORDER_STATUS__IN_PROCESS = '#66ffeb';
export const BACKGROUND_COLOR__ORDER_STATUS__ON_ITS_WAY = '#6bd5ff';
export const BACKGROUND_COLOR__ORDER_STATUS__PARTIALLY_COMPLETED = '#0b82de';
export const BACKGROUND_COLOR__ORDER_STATUS__COMPLETED = '#0cb51f';

export const FOREGROUND_COLOR__ORDER_STATUS__RECEIVED = '#c76805';
export const FOREGROUND_COLOR__ORDER_STATUS__ASSIGNED = '#000';
export const FOREGROUND_COLOR__ORDER_STATUS__IN_PROCESS = '#000';
export const FOREGROUND_COLOR__ORDER_STATUS__ON_ITS_WAY = '#000';
export const FOREGROUND_COLOR__ORDER_STATUS__PARTIALLY_COMPLETED = '#fff';
export const FOREGROUND_COLOR__ORDER_STATUS__COMPLETED = '#fff';