export const EDITOR_TYPE_INLINE = 'EDITOR_TYPE_INLINE';
export const EDITOR_TYPE_WINDOWED = 'EDITOR_TYPE_WINDOWED';
export const EDITOR_TYPE_SMART = 'EDITOR_TYPE_SMART';
export const EDITOR_TYPE_PLAIN = 'EDITOR_TYPE_PLAIN';