export const ROW_HEADER_ID = 'ROW_HEADER_ID';
export const SORT_ASCENDING = 'ASC';
export const SORT_DESCENDING = 'DESC';
export const SELECTION_MODE_SINGLE = 'SELECTOR_MODE_SINGLE';
export const SELECTION_MODE_MULTI = 'SELECTOR_MODE_MULTI';