export const NOTIFICATION_TYPE__ORDER_STATUS_CHANGE = 1;
export const NOTIFICATION_TYPE__ORDER_MODIFICATION = 2;
export const NOTIFICATION_TYPE__NEW_ORDER = 3;
export const NOTIFICATION_TYPE__SHOW_GRATUITY = 4;
export const NOTIFICATION_TYPE__CHAT = 5;
export const NOTIFICATION_TYPE__END_SHIFT_NOW = 6;
