export const PM_SCHEDULE_MODES__HISTORICAL_USAGE = 1;
export const PM_SCHEDULE_MODES__EXPECTED_USAGE = 2;
export const PM_SCHEDULE_MODES__NO_ESTIMATION = 3;
export const PM_SCHEDULE_MODES__WILL_CALL = 4;
