export const PROGRESS__NONE_FOUND = 'NONE_FOUND';
export const PROGRESS__IN_PROCESS = 'IN_PROCESS';
export const PROGRESS__COMPLETED = 'COMPLETED';
export const PROGRESS__FAILED = 'FAILED';
export const PROGRESS__STUCK = 'STUCK';
export const PROGRESS__UNSTUCK = 'UNSTUCK';

export const ASYNC_OPERATION_MODES__INIT = 'INIT';
export const ASYNC_OPERATION_MODES__START = 'START';
export const ASYNC_OPERATION_MODES__PROCESSING = 'PROCESSING';
export const ASYNC_OPERATION_MODES__RESULTS = 'RESULTS';