export const REPORT_QUEUE_STATUS__ALL = 'ALL';
export const REPORT_QUEUE_STATUS__PENDING = 'PENDING';
export const REPORT_QUEUE_STATUS__IN_PROCESS = 'IN_PROCESS';
export const REPORT_QUEUE_STATUS__COMPLETED = 'COMPLETED';
export const REPORT_QUEUE_STATUS__FAILED = 'FAILED';
