import * as appStyles from '../../Constants/Styles';
import _ from 'lodash';

const
	DEFAULT_FONTSIZE = 15,
	WHITE = '#fff';

const defaults = {
	HEADER_PX: 3,
	HEADER_PY: 1,
	HEADER_ICON_SIZE: 13,
	HEADER_ICON_COLOR: WHITE,
	HEADER_TEXT_FONTSIZE: 15,
	HEADER_TEXT_COLOR: WHITE,
	FIELDSET_FONTSIZE: DEFAULT_FONTSIZE,
	LABEL_WIDTH: '170px',
	LABEL_FONTSIZE: DEFAULT_FONTSIZE,
	FILE_INPUT_FONTSIZE: DEFAULT_FONTSIZE,
	INPUT_BG: WHITE,
	INPUT_FONTSIZE: DEFAULT_FONTSIZE,
	TEXTAREA_FONTSIZE: DEFAULT_FONTSIZE,
	TEXTAREA_HEIGHT: 130,
	COMBO_HEIGHT: '40px',
	COMBO_INPUT_FONTSIZE: DEFAULT_FONTSIZE,
	COMBO_INPUT_BG: WHITE,
	COMBO_INPUT_FOCUS_BG: '#ffd',
	COMBO_TRIGGER_BG: WHITE,
	COMBO_TRIGGER_HOVER_BG: 'trueGray.300',
	GRID_HEADER_BG: '#eee',
	GRID_HEADER_HOVER_BG: '#ddd',
	GRID_HEADER_FONTSIZE: DEFAULT_FONTSIZE,
	GRID_ROW_BG: WHITE,
	GRID_ROW_SELECTED_BG: 'selected',
	GRID_NAV_COLUMN_COLOR: '#aaa',
	GRID_CELL_FONTSIZE: DEFAULT_FONTSIZE,
	GRID_TOOLBAR_ITEMS_COLOR: 'trueGray.800',
	GRID_TOOLBAR_ITEMS_DISABLED_COLOR: 'disabled',
	GRID_TOOLBAR_ITEMS_ICON_SIZE: 'sm',
	COLOR_READOUT_FONTSIZE: DEFAULT_FONTSIZE,
	FILE_READOUT_FONTSIZE: DEFAULT_FONTSIZE,
	NUMBER_FONTSIZE: DEFAULT_FONTSIZE,
	DATE_READOUT_FONTSIZE: DEFAULT_FONTSIZE,
	TAB_BAR_BG: 'primary.700',
	TAB_BG: 'primary.300',
	TAB_COLOR: WHITE,
	TAB_ACTIVE_BG: 'trueGray.200',
	TAB_ACTIVE_COLOR: 'primary.800',
	TAB_FONTSIZE: DEFAULT_FONTSIZE,
};

export default _.merge(defaults, appStyles);

